baseURL = "https://www.diu.life/"
languageCode = "zh-cn"
title = "ä¸¢å“¥"
theme = "papermod"
defaultContentLanguage = "zh"
hasCJKLanguage = true


[pagination]
  pagerSize = 10


[params]
  author = "ä¸¢å“¥"
  description = "è®°å½•ä¸ªäººæˆé•¿ã€æ€è€ƒå’Œç”Ÿæ´»æ„Ÿæ‚Ÿã€ç‹¬ç«‹å¼€å‘ç¢ç¢æ‹ã€å‡ºæµ·æ—¥è®°"
  keywords = ["ä¸¢å“¥", "diuge", "ç‹¬ç«‹å¼€å‘", "å‡ºæµ·"]
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  comments = false
  mainSections = ["posts"]

  # å¼€å¯é¦–é¡µæ–‡ç« åˆ—è¡¨
  # homeInfoParams = { Title = "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ ğŸ‘‹", Content = "è¿™æ˜¯æˆ‘çš„ä¸ªäººæŠ€æœ¯åšå®¢ï¼Œè®°å½•å¼€å‘ã€æ€è€ƒå’Œç”Ÿæ´»ã€‚" }

[menu]
  [[menu.main]]
    name = "é¦–é¡µ"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "æ–‡ç« "
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "ç‹¬ç«‹å¼€å‘"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "æ•™ç¨‹"
    url = "/lessons/"
    weight = 4

  [[menu.main]]
    name = "å…³äº"
    url = "/about/"
    weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    noClasses = false

